function markers = processHindlimbMarkers(...
    markers,...
    fs,...
    vMax,...
    lengthTol,...
    minValidRun,...
    maxInterpGap,...
    cutoff,...
    filterOrder)

if nargin < 2, fs = 120; end
if nargin < 3, vMax = 1000; end
if nargin < 4, lengthTol = 3; end
if nargin < 5, minValidRun = 1; end
if nargin < 6, maxInterpGap = 12; end
if nargin < 7, cutoff = 20; end
if nargin < 8, filterOrder = 4; end

%% Velocity rejection

names = fieldnames(markers);

for k = 1:numel(names)
    markers.(names{k}) = rejectVelocitySpikes(...
        markers.(names{k}),...
        fs,...
        vMax);
end

%% Bone length consistency

chain = {'RASI','RightHIP','RightKNEE','RightANKLE','RightMET'};

for k=1:length(chain)-1

    a = chain{k};
    b = chain{k+1};

    [markers.(a),markers.(b)] = ...
        enforceBoneLength(...
        markers.(a),...
        markers.(b),...
        lengthTol);
end

%% Remove short runs

for k=1:numel(names)
    markers.(names{k}) = ...
        removeShortValidRuns(...
        markers.(names{k}),...
        minValidRun);
end

%% Interpolate

for k=1:numel(names)
    markers.(names{k}) = ...
        interpolateShortGaps(...
        markers.(names{k}),...
        maxInterpGap);
end

%% Filter

for k=1:numel(names)

    markers.(names{k}) = ...
        butterLowpassMarker(...
        markers.(names{k}),...
        fs,...
        cutoff,...
        filterOrder);
end

end