function markerF = butterLowpassMarker(...
    marker,...
    fs,...
    cutoff,...
    order)

markerF = marker;

[b,a] = butter(...
    order,...
    cutoff/(fs/2),...
    'low');

for dim=1:3

    x = marker(:,dim);

    valid = ~isnan(x);

    if sum(valid) < order*3
        continue
    end

    xFilled = x;

    xFilled(~valid) = interp1(...
        find(valid),...
        x(valid),...
        find(~valid),...
        'linear',...
        'extrap');

    xFiltered = filtfilt(...
        b,...
        a,...
        xFilled);

    xFiltered(~valid) = NaN;

    markerF(:,dim)=xFiltered;

end

end