function exportGRFMot( ...
    motFilename,...
    Fx,Fy,Fz,...
    CoPx,CoPy,CoPz,...
    Mx,My,Mz,...
    outputMotionFolder,...
    frequency,...
    startFrame,...
    endFrame)

nFrames = endFrame-startFrame+1;

%nInterp = 101; % to normalize the stance phase
nInterp = nFrames; % to keep the original number 

duration = (nFrames-1)/frequency;
time = linspace(0, duration, nInterp);

fid = fopen(fullfile(outputMotionFolder,motFilename),'w');

fprintf(fid,'name GRF\n');
fprintf(fid,'datacolumns 10\n');
fprintf(fid,'datarows %d\n',nInterp);
fprintf(fid,'endheader\n');

fprintf(fid,...
['time\t',...
'1_ground_force_vx\t',...
'1_ground_force_vy\t',...
'1_ground_force_vz\t',...
'1_ground_force_px\t',...
'1_ground_force_py\t',...
'1_ground_force_pz\t',...
'1_ground_torque_x\t',...
'1_ground_torque_y\t',...
'1_ground_torque_z\n']);

for i=1:nInterp

    fprintf(fid,...
        ['%.10f\t%.10f\t%.10f\t%.10f\t',...
         '%.10f\t%.10f\t%.10f\t',...
         '%.10f\t%.10f\t%.10f\n'],...
         time(i),...
         Fx(i),Fy(i),Fz(i),...
         CoPx(i),CoPy(i),CoPz(i),...
         Mx(i),My(i),Mz(i));

end

fclose(fid);

end
