function signalNorm = normalizeCycle(signal,fs,nPoints)

if nargin<3
    nPoints = 101;
end

oldX = linspace(0,...
    length(signal)/fs,...
    length(signal));

newX = linspace(0,...
    length(signal)/fs,...
    nPoints);

signalNorm = interp1(...
    oldX,...
    signal,...
    newX,...
    'linear');

end