function [Rlist,Tlist] = ...
    processStanceTrajectories( ...
    xyz,...
    frames,...
    markerNames,...
    baseFilename,...
    markerTRCNames,...
    modelPath,...
    frequency,...
    outputMotionFolder,...
    MIN_SPEED)

Rlist = {};
Tlist = {};

for i = 1:size(frames,1)

    f0 = frames(i,1);
    f1 = frames(i,2);

    [xyzAligned,R,T] = ...
        alignMarkersToModel( ...
        xyz,...
        markerNames,...
        markerTRCNames,...
        modelPath,...
        f0,...
        f1);

    [~,speed] = ...
        computeVelocity( ...
        xyz.RightHIP(f0:f1,:),...
        frequency);

    meanSpeed = ...
        mean(speed,'omitnan')/1000;

    if meanSpeed < MIN_SPEED

        fprintf( ...
        'Cycle %d skipped (%.2f m/s)\n',...
        i,...
        meanSpeed);

        continue

    end

    fprintf( ...
    'Exporting cycle %d (%.2f m/s)\n',...
    i,...
    meanSpeed);

    trcFile = ...
        sprintf( ...
        '%s_StanceNorm_%02d.trc',...
        baseFilename,...
        i);

    exportNormalizedToTRC( ...
        trcFile,...
        xyzAligned,...
        markerNames,...
        markerTRCNames,...
        f0,...
        f1,...
        frequency,...
        outputMotionFolder);

    Rlist{end+1}=R;
    Tlist{end+1}=T;

end

end